### ISSUE TITLE
Not sharing source code...

### ISSUE THREAD

**Issue by GutZuFusss** [ChillerDragon/ddnet7-client#1]
susserspicerious?

**Comment by ChillerDragon** [comment]
https://github.com/ddnet/ddnet/pull/5949

This is a build of my [pr_07_client](https://github.com/ChillerDragon/ddnet/tree/pr_07_client) branch in ChillerDragon/ddnet.
The pullrequest is pending since one year in ddnet so I decided doing a release page for non technical people who want to try it out.

**Comment by GutZuFusss** [comment]
thank chieler
